/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }

    maven {
        url = uri("https://repo.extendedclip.com/content/repositories/placeholderapi/")
    }

    maven {
        url = uri("https://libraries.minecraft.net/")
    }

    maven {
        url = uri("https://repo.codemc.io/repository/maven-snapshots/")
    }

    maven {
        url = uri("https://repo.codemc.io/repository/maven-releases/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.net.kyori.adventure.platform.bukkit)
    api(libs.org.bstats.bstats.bukkit)
    api(libs.net.kyori.adventure.api)
    api(libs.io.github.revxrsal.lamp.common)
    api(libs.io.github.revxrsal.lamp.bukkit)
    api(libs.net.kyori.adventure.text.minimessage)
    compileOnly(libs.org.spigotmc.spigot.api)
    compileOnly(libs.com.mojang.authlib)
    compileOnly(libs.com.github.retrooper.packetevents.spigot)
    compileOnly(libs.me.clip.placeholderapi)
}

group = "hhitt.org.example"
version = "2.3.3"
description = "FancyGlow"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
